version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py  # Make sure this path is correct

python:
  install:
    - requirements: docs/requirements.txt  # Ensure this file exists
